### ISSUE TITLE
Wrong results with some datasets and builders

### ISSUE THREAD

**Issue by cduch9** [ingowald/cudaKDTree#17] opened 2024-01-03 23:02 UTC
Hi! 
I am starting to play with your very interesting work. However, I sometimes get the wrong result. Here are some cases:

1) Using builder_thrust() on 90166 random points: the right closest point is found --> OK!
2) Using buildTree_inPlace() on the same 90166 points: the right closest point is found, but the returned ID is different. Normal?
3) Using builder_thrust() on 90167 points (same as above + 1 new): NO closest point is found :(
4) Using buildTree_inPlace() on the same 90167 points: the right closest point is found --> OK!
5) Using buildTree_bitonic() on those 90166 and 90167 points : NO closest point is found :(

I would have expected the tree to be exactly the same with the 3 builders. Should it be the case?
Do you know of an existing problem that could cause this behavior? Where to look for?

Thank you!
Claude

Notes:
- I can compare your result with my own "Closest Point" algorithm working on the CPU. Much slower but proven to be robust.
- I tried all tree query methods. It shows that the problem is with the builder.
- My points are generated at random between -100 and +100 in all 3 dimensions. I can provide them if needed.

**Comment by ingowald** [comment] 2024-01-04 11:30
Oh, very interesting. I've done extensive verification with both different builders and against an independent BVH alternative code base, but maybe something slipped through!
Can you provide as much reproducer info as possible? I'd like to catch this ASAP...

**Comment by cduch9** [comment] 2024-01-04 15:48
- Point are generated like this (nb_= 90167, seed_= 33):

```
	void GenerateRandomPoints( size_t nb_, int seed_, std::vector< float3 >& destPts_ )
	{
		const double maxVal = 100.0;
		const double scale  = 2.0f * maxVal / RAND_MAX;

		destPts_.resize( nb_ );
		std::srand( seed_ );

		for ( size_t i = 0; i < nb_; i++ )
		{
			destPts_[ i ].x = static_cast< float >( std::rand() * scale - maxVal );
			destPts_[ i ].y = static_cast< float >( std::rand() * scale - maxVal );
			destPts_[ i ].z = static_cast< float >( std::rand() * scale - maxVal );
		}
	}
```
- It should start like this:
	[0]	{x=-99.1088562 y=-87.9879150 z=27.7626877 }	float3
	[1]	{x=-38.3892326 y=31.5713978 z=-37.0891457 }	float3
	[2]	{x=-22.0435200 y=-92.5473785 z=89.4833221 }	float3
	[3]	{x=48.5274811 y=-94.0671997 z=80.3888092 }	float3
	[4]	{x=-33.9030113 y=34.4157219 z=95.2085953 }	float3

- The querry point is {x=-98.4496613 y=76.9219055 z=25.8888512 }

- The "cutOffRadius" is 5.0

- The closest point should be at squared distance of 2.8466301

**Comment by ingowald** [comment] 2024-01-04 17:40
Thx! I'll be in a plane all day tomorrow, but will look at that asap

**Comment by cduch9** [comment] 2024-01-05 16:14
I found it! The problem is is only present in the Visual Studio version. That is probably why you did not see it. The function levelOf() should be replaced by one of the followings: 

Option #1:

```
static inline int __builtin_clzll( unsigned long long x )
{
#ifdef _WIN64
	return ( int )_lzcnt_u64( x );
#else
	Not tested yet
	return !!unsigned( x >> 32 ) ? __builtin_clz( ( unsigned )( x >> 32 ) ) : 32 + __builtin_clz( ( unsigned )x );
#endif // ifdef _WIN64
}

inline static __host__ __device__ int levelOf( int nodeID )
{
#ifdef __CUDA_ARCH__
	int k = 63 - __clzll( nodeID + 1 );
#else
	int k = 63 - __builtin_clzll( nodeID + 1 );
#endif // ifdef __CUDA_ARCH__
	return k;
}
```
Option #2:

```
inline static __host__ __device__ int levelOf( int nodeID )
{
#ifdef __CUDA_ARCH__
	int k = 63 - __clzll( nodeID + 1 );
#elif defined( _MSC_VER )
	#ifdef _WIN64
		unsigned long bs;
		_BitScanReverse64( &bs, nodeID + 1 );
		int k = bs;
	#else
		unsigned long bs;
		_BitScanReverse( &bs, nodeID + 1 );
		int k = 31 - bs;                should probably be "k = bs"
	#endif // ifdef _WIN64
#else
	int k = 63 - __builtin_clzll( nodeID + 1 );
#endif // ifdef __CUDA_ARCH__
	return k;
}
```
_BitScanReverse was used in reverse and, in 64 bits, _BitScanReverse64 must be used.

**Comment by cduch9** [comment] 2024-01-05 16:26
Good info is found here : https://gist.github.com/pps83/3210a2f980fd02bb2ba2e5a1fc4a2ef0#file-ctz_clz-cpp

Note that I will use that simpler version for the moment (does not work in win32) :

```
 inline static __host__ __device__ int levelOf( int nodeID )
 {
#ifdef __CUDA_ARCH__
        return 63 - __clzll( nodeID + 1 );
#elif defined( _WIN64 )
        return 63 -  static_cast< int >( _lzcnt_u64( nodeID + 1 ) );
#else
        return 63 - __builtin_clzll( nodeID + 1 );
#endif // ifdef __CUDA_ARCH__
 }

```

**Comment by ingowald** [comment] 2024-01-05 21:38
Ahhhhh..... so glad to hear that. I actually spent some of the time on my flight trying to reproduce that problem on my laptop, and was already stumped that I couldn't - but my laptop runs linux, so that explains a lot. I'm a bit confused that apparently the test data points I generated are different from those you had - literal copy of your GeneratePoints, same seed, etc - but if the clz fixes it than that's good with me.
I'll actually have to check a few other codes as well, then - I'm fairly sure i use clz in some other codes as well.

Thanks for finding that, that's super helpful!

**Comment by cduch9** [comment] 2024-01-05 22:19
Your welcome! 

Please note that I have not tested the Win32 implementation. Also, I don't think the randomizer should give the same results with different hardwares/compilers. 

In the coming weeks/months, I hope to do some performance testing. I only do this in my spare time.

My main goal is to replace an old algorithm that finds ALL nearest neighbors in a given volume. Unlike KNN, the number K is unknown. I don't yet know how to do it efficiently. I guess assigning a huge K would not work well. 

Any ideas would be welcome!

**Comment by ingowald** [comment] 2024-01-06 18:38
Hm. Looking at the above code I think the problem is less the BitScanReverse64 vs BitScanReverse, and more the "31-bs" vs "bs". In your 64-bit version (which I understand is the one you tested and which works) you return bs - not "31-bs" as my linux variants do, and reading through the MS docs on bitscan it realy seems to come down to the bitscan"reverse" counting from the _lowest_ bit vs the linux clz variants countint the _leading_ (ie, top) zeroes.
So "probably" we wouldn't even need any special 64/32 bit ifdef branching, and only need to remove the "31-" ...
i'll push that, and see if I can find a windows machine to test it on.

**Comment by ingowald** [comment] 2024-01-07 13:32
just realized it's not even 'only' a windows/linux issue, but that you apparently build on the host - all my test cases run on the gpu.
could you have a look at my iw/issue5 branch i just pushed, and see if that code works for you? if so i'll merge; i just don't want to mark as completed until i know for sure that it fixes it

**Comment by cduch9** [comment] 2024-01-08 18:31
1) About BitScanReverse vs _BitScanReverse64 : you are right, it makes no difference. Only removing the "31-" is required. Note that "long" is 4 bytes on x64 Windows and 8 bytes on x64 Linux. The _BitScanReverse64 version ensure that 8 bytes is used on Windows as well... but it is not necessary here.

2) About GPU vs CPU : most calls to BinaryTree::levelOf() are on the GPU exept 
- buildTree_thrust -> BinaryTree::numLevelsFor -> BinaryTree::levelOf -> impacts the tree itself
- checkRec -> BinaryTree::levelOf -> Only impacts the checking. No big deal. I only perfor the check in debug.

3) Your changes in the "issue5" branch work for me. Thanks!

**Comment by ingowald** [comment] 2024-01-08 18:44
Thank you - much appreciated! I'll merge into master later today.

PS: if you want to chat algorithms/best options for your region queries, let me know. Happy to chat (ingowald at gmail)

**Comment by ingowald** [comment] 2024-01-09 14:58
fixed in latest master

**Closed as completed** 2024-01-09 14:58 UTC
